//
//  LoginModels.swift
//  Clean First
//
//  Created by Ilya Paddubny on 16.09.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    
    // MARK: - Use cases
    
    enum LoginAction {
        struct Request {
            let username: String
            let password: String
        }
        
        struct Response {
            let success: Bool
            let errorMessage: String?
        }
        
        struct ViewModel {
            let successMessage: String?
            let errorMessage: String?
        }
    }
}
