//
//  LoginInteractor.swift
//  Clean First
//
//  Created by Ilya Paddubny on 16.09.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func doSomething(request: Login.LoginAction.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Login.LoginAction.Request)
  {
//    worker = LoginWorker()
//    worker?.doSomeWork()
    
//    let response = Login.LoginAction.Response()
//    presenter?.presentSomething(response: response)
  }
}
