//
//  StartScreenPresenter.swift
//  Clean First
//
//  Created by Ilya Paddubny on 24.09.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartScreenPresentationLogic
{
  func presentLogin(response: StartScreen.Login.Response)
  func presentRegister(response: StartScreen.Register.Response)
}

class StartScreenPresenter: StartScreenPresentationLogic
{
    weak var viewController: StartScreenDisplayLogic?
    
    func presentLogin(response: StartScreen.Login.Response) {
        viewController?.displayLoginScreen(viewModel: StartScreen.Login.ViewModel())
    }
    
    func presentRegister(response: StartScreen.Register.Response) {
        viewController?.displayRegisterScreen(viewModel: StartScreen.Register.ViewModel())
    }
    
  
  
}
