//
//  StartScreenModels.swift
//  Clean First
//
//  Created by Ilya Paddubny on 24.09.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum StartScreen {
    enum Login {
        struct Request {}
        struct Response {}
        struct ViewModel {}
    }

    enum Register {
        struct Request {}
        struct Response {}
        struct ViewModel {}
    }
}
