//
//  StartScreenRouter.swift
//  Clean First
//
//  Created by Ilya Paddubny on 24.09.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StartScreenRoutingLogic {
    func routeToLogin()
    func routeToRegister()
}

protocol StartScreenDataPassing {
    var dataStore: StartScreenDataStore? { get }
}

class StartScreenRouter: NSObject, StartScreenRoutingLogic, StartScreenDataPassing, UIViewControllerTransitioningDelegate {
    
    weak var viewController: StartScreenViewController?
    var dataStore: StartScreenDataStore?
    
    // MARK: - Routing to Login Screen
    func routeToLogin() {
        let loginVC = LoginViewController()
        navigateToLogin(source: viewController!, destination: loginVC)
    }
    
    // MARK: - Routing to Register Screen
    func routeToRegister() {
        let registerVC = RegisterViewController() 
        navigateToRegister(source: viewController!, destination: registerVC)

    }
    
    // MARK: - Navigation Methods
    
    private func navigateToLogin(source: StartScreenViewController, destination: LoginViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    private func navigateToRegister(source: StartScreenViewController, destination: RegisterViewController) {
//        source.navigationController?.pushViewController(destination, animated: true)
        //TODO: add the modal view conntroller here
        destination.modalPresentationStyle = .custom
        destination.transitioningDelegate = self
        source.present(destination, animated: true, completion: nil)
    }
}
