//
//  StartScreenInteractor.swift
//  Clean First
//
//  Created by Ilya Paddubny on 24.09.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartScreenBusinessLogic
{
  func login(request: StartScreen.Login.Request)
  func register(request: StartScreen.Register.Request)
}

protocol StartScreenDataStore
{
    
}

class StartScreenInteractor: StartScreenBusinessLogic, StartScreenDataStore
{
    func login(request: StartScreen.Login.Request) {
        let response = StartScreen.Login.Response()
        presenter?.presentLogin(response: response)
    }
    
    func register(request: StartScreen.Register.Request) {
        let response = StartScreen.Register.Response()
        presenter?.presentRegister(response: response)
    }
    
  var presenter: StartScreenPresentationLogic?
  var worker: StartScreenWorker?
  
}
